### ISSUE TITLE
Auth by webview bug

### ISSUE THREAD

**Issue by shysh** [birdcage/soundcloud-web-api-android#8]
AuthenticationActivity WebViewAuthClient must use shouldOverrideUrlLoading() method for checking redirectUri

Thanks a lot for your work :)

**Comment by jacoblubecki** [comment]
No problem!

I think this is handled by overriding `onPageFinished`. Why do I need the override in `shouldOverrideUrlLoading`?

To clarify: I'm only interested in knowing that the page tried to load the redirect in `onPageFinished`. Once this happens, it sends the data back by finishing the activity with a result that can be used for authentication. Where exactly does the need for overriding the URL loading come in?
